export const COUNTRIES = [
  { code: 'US', name: 'United States', region: 'Americas' },
  { code: 'CN', name: 'China', region: 'Asia' },
  { code: 'DE', name: 'Germany', region: 'Europe' },
  { code: 'JP', name: 'Japan', region: 'Asia' },
  { code: 'IN', name: 'India', region: 'Asia' },
  { code: 'GB', name: 'United Kingdom', region: 'Europe' },
  { code: 'FR', name: 'France', region: 'Europe' },
  { code: 'BR', name: 'Brazil', region: 'Americas' },
  { code: 'CA', name: 'Canada', region: 'Americas' },
  { code: 'KR', name: 'South Korea', region: 'Asia' },
  { code: 'RU', name: 'Russia', region: 'Europe' },
  { code: 'AU', name: 'Australia', region: 'Oceania' },
  { code: 'ES', name: 'Spain', region: 'Europe' },
  { code: 'IT', name: 'Italy', region: 'Europe' },
  { code: 'MX', name: 'Mexico', region: 'Americas' },
  { code: 'ID', name: 'Indonesia', region: 'Asia' },
  { code: 'TR', name: 'Turkey', region: 'Europe' },
  { code: 'NL', name: 'Netherlands', region: 'Europe' },
  { code: 'SA', name: 'Saudi Arabia', region: 'Middle East' },
  { code: 'CH', name: 'Switzerland', region: 'Europe' },
  { code: 'SE', name: 'Sweden', region: 'Europe' },
  { code: 'NO', name: 'Norway', region: 'Europe' },
  { code: 'PL', name: 'Poland', region: 'Europe' },
  { code: 'ZA', name: 'South Africa', region: 'Africa' },
  { code: 'NG', name: 'Nigeria', region: 'Africa' },
  { code: 'EG', name: 'Egypt', region: 'Africa' },
  { code: 'AR', name: 'Argentina', region: 'Americas' },
  { code: 'TH', name: 'Thailand', region: 'Asia' },
  { code: 'MY', name: 'Malaysia', region: 'Asia' },
  { code: 'PH', name: 'Philippines', region: 'Asia' },
];

export const REGIONS = [...new Set(COUNTRIES.map(c => c.region))].sort();
