import type { MetricCatalogEntry } from './types'

export const catalog: MetricCatalogEntry[] = [
  // ── ECONOMIC ──────────────────────────────────────────────────────────────
  {
    id: 'cpi-inflation',
    name: 'CPI Inflation',
    category: 'economic',
    unit: '% YoY',
    granularity: 'monthly',
    goodDirection: 'neutral',
    source: { agency: 'BLS', program: 'CPI', url: 'https://fred.stlouisfed.org/series/CPIAUCSL' },
    seriesId: 'CPIAUCSL',
    transform: 'yoyPercent',
    fetchFn: 'fred',
    description: 'Consumer Price Index, All Urban Consumers — year-over-year % change',
  },
  {
    id: 'unemployment-rate',
    name: 'Unemployment Rate',
    category: 'economic',
    unit: '%',
    granularity: 'monthly',
    goodDirection: 'down',
    source: { agency: 'BLS', program: 'CPS', url: 'https://fred.stlouisfed.org/series/UNRATE' },
    seriesId: 'UNRATE',
    transform: 'identity',
    fetchFn: 'fred',
    description: 'Civilian unemployment rate, seasonally adjusted',
  },
  {
    id: 'nonfarm-payrolls',
    name: 'Nonfarm Payrolls',
    category: 'economic',
    unit: 'K MoM',
    granularity: 'monthly',
    goodDirection: 'up',
    source: { agency: 'BLS', program: 'CES', url: 'https://fred.stlouisfed.org/series/PAYEMS' },
    seriesId: 'PAYEMS',
    transform: 'momChange',
    fetchFn: 'fred',
    description: 'Total nonfarm payrolls — month-over-month change in thousands',
  },
  {
    id: 'real-gdp-growth',
    name: 'Real GDP Growth',
    category: 'economic',
    unit: '% annualized',
    granularity: 'quarterly',
    goodDirection: 'up',
    source: { agency: 'BEA', program: 'NIPA', url: 'https://fred.stlouisfed.org/series/A191RL1Q225SBEA' },
    seriesId: 'A191RL1Q225SBEA',
    transform: 'identity',
    fetchFn: 'fred',
    description: 'Real GDP — percent change at annual rate, seasonally adjusted',
  },
  {
    id: 'avg-hourly-earnings',
    name: 'Avg Hourly Earnings',
    category: 'economic',
    unit: '% YoY',
    granularity: 'monthly',
    goodDirection: 'up',
    source: { agency: 'BLS', program: 'CES', url: 'https://fred.stlouisfed.org/series/CES0500000003' },
    seriesId: 'CES0500000003',
    transform: 'yoyPercent',
    fetchFn: 'fred',
    description: 'Average hourly earnings, all private employees — YoY % change',
  },
  {
    id: 'job-openings',
    name: 'Job Openings (JOLTS)',
    category: 'economic',
    unit: 'thousands',
    granularity: 'monthly',
    goodDirection: 'up',
    source: { agency: 'BLS', program: 'JOLTS', url: 'https://fred.stlouisfed.org/series/JTSJOL' },
    seriesId: 'JTSJOL',
    transform: 'identity',
    fetchFn: 'fred',
    description: 'Job openings, total nonfarm',
  },
  {
    id: 'fed-funds-rate',
    name: 'Fed Funds Rate',
    category: 'economic',
    unit: '%',
    granularity: 'daily',
    goodDirection: 'neutral',
    source: { agency: 'Federal Reserve', program: 'H.15', url: 'https://fred.stlouisfed.org/series/DFF' },
    seriesId: 'DFF',
    transform: 'identity',
    fetchFn: 'fred',
    description: 'Federal funds effective rate',
  },
  {
    id: 'treasury-10yr',
    name: '10-Yr Treasury Yield',
    category: 'economic',
    unit: '%',
    granularity: 'daily',
    goodDirection: 'neutral',
    source: { agency: 'Federal Reserve', program: 'H.15', url: 'https://fred.stlouisfed.org/series/DGS10' },
    seriesId: 'DGS10',
    transform: 'identity',
    fetchFn: 'fred',
    description: '10-year Treasury constant maturity rate',
  },
  {
    id: 'federal-debt',
    name: 'Federal Debt',
    category: 'economic',
    unit: '$T',
    granularity: 'daily',
    goodDirection: 'down',
    source: { agency: 'Treasury', program: 'FiscalData', url: 'https://fiscaldata.treasury.gov/datasets/debt-to-the-penny/' },
    fetchFn: 'treasury',
    description: 'Total public debt outstanding',
  },
  {
    id: 'federal-deficit',
    name: 'Federal Deficit/Surplus',
    category: 'economic',
    unit: '$B monthly',
    granularity: 'monthly',
    goodDirection: 'up',
    source: { agency: 'Treasury', program: 'MTS', url: 'https://fred.stlouisfed.org/series/MTSDS133FMS' },
    seriesId: 'MTSDS133FMS',
    transform: 'identity',
    fetchFn: 'fred',
    description: 'Federal surplus or deficit, monthly (negative = deficit)',
  },
  {
    id: 'trade-balance',
    name: 'Trade Balance',
    category: 'economic',
    unit: '$B',
    granularity: 'monthly',
    goodDirection: 'neutral',
    source: { agency: 'BEA', program: 'BOP', url: 'https://fred.stlouisfed.org/series/BOPGSTB' },
    seriesId: 'BOPGSTB',
    transform: 'identity',
    fetchFn: 'fred',
    description: 'Trade balance: goods and services',
  },
  {
    id: 'median-household-income',
    name: 'Median Household Income',
    category: 'economic',
    unit: '$',
    granularity: 'annual',
    goodDirection: 'up',
    source: { agency: 'Census', program: 'CPS ASEC', url: 'https://fred.stlouisfed.org/series/MEHOINUSA672N' },
    seriesId: 'MEHOINUSA672N',
    transform: 'identity',
    fetchFn: 'fred',
    description: 'Real median household income, inflation-adjusted 2023 dollars',
  },
  {
    id: 'labor-force-participation',
    name: 'Labor Force Participation',
    category: 'economic',
    unit: '%',
    granularity: 'monthly',
    goodDirection: 'up',
    source: { agency: 'BLS', program: 'CPS', url: 'https://fred.stlouisfed.org/series/CIVPART' },
    seriesId: 'CIVPART',
    transform: 'identity',
    fetchFn: 'fred',
    description: 'Civilian labor force participation rate',
  },

  // ── DEMOGRAPHIC ───────────────────────────────────────────────────────────
  {
    id: 'us-population',
    name: 'US Population',
    category: 'demographic',
    unit: 'M',
    granularity: 'monthly',
    goodDirection: 'neutral',
    source: { agency: 'Census/BEA', program: 'Population Estimates', url: 'https://fred.stlouisfed.org/series/POPTHM' },
    seriesId: 'POPTHM',
    transform: 'identity',
    fetchFn: 'fred',
    scale: 0.001,
    description: 'US resident population (thousands in FRED, displayed in millions)',
  },
  {
    id: 'poverty-rate',
    name: 'Poverty Rate',
    category: 'demographic',
    unit: '%',
    granularity: 'annual',
    goodDirection: 'down',
    source: { agency: 'Census', program: 'ACS 1-Year', url: 'https://www.census.gov/programs-surveys/acs' },
    fetchFn: 'census-poverty',
    description: 'Poverty rate — ACS 1-Year S1701; 2020 not published (pandemic gap)',
  },
  {
    id: 'homeownership-rate',
    name: 'Homeownership Rate',
    category: 'demographic',
    unit: '%',
    granularity: 'quarterly',
    goodDirection: 'neutral',
    source: { agency: 'Census', program: 'HVS', url: 'https://fred.stlouisfed.org/series/RHORUSQ156N' },
    seriesId: 'RHORUSQ156N',
    transform: 'identity',
    fetchFn: 'fred',
    description: 'Homeownership rate for the United States',
  },

  // ── POLITICAL ─────────────────────────────────────────────────────────────
  {
    id: 'campaign-fundraising',
    name: 'Total Campaign Fundraising',
    category: 'political',
    unit: '$B per cycle',
    granularity: 'cycle',
    goodDirection: 'neutral',
    source: { agency: 'FEC', program: 'Campaign Finance', url: 'https://www.fec.gov/data/' },
    fetchFn: 'fec-totals',
    description: 'Total federal campaign receipts by 2-year election cycle',
  },
  {
    id: 'bills-enacted',
    name: 'Bills Enacted per Congress',
    category: 'political',
    unit: 'bills',
    granularity: 'cycle',
    goodDirection: 'neutral',
    source: { agency: 'Congress.gov', program: 'Legislative', url: 'https://api.congress.gov' },
    fetchFn: 'congress-bills',
    description: 'Number of bills enacted per 2-year Congress (93rd–current)',
  },
  {
    id: 'party-composition',
    name: 'House Party Composition',
    category: 'political',
    unit: 'D seats',
    granularity: 'cycle',
    goodDirection: 'neutral',
    source: { agency: 'House.gov', program: 'Historical Tables', url: 'https://history.house.gov/Institution/Party-Divisions/Party-Divisions/' },
    fetchFn: 'static-party',
    description: 'Democratic seats in the US House of Representatives by Congress',
  },
  {
    id: 'voter-turnout',
    name: 'Voter Turnout (VEP)',
    category: 'political',
    unit: '%',
    granularity: 'cycle',
    goodDirection: 'up',
    source: { agency: 'Census', program: 'CPS Voting Supplement', url: 'https://www.census.gov/topics/public-sector/voting.html' },
    fetchFn: 'static-turnout',
    description: 'Voting Eligible Population (VEP) turnout rate, presidential and midterm elections',
  },
]

export function getMetric(id: string): MetricCatalogEntry | undefined {
  return catalog.find(m => m.id === id)
}

export function getMetricsByCategory(
  category: MetricCatalogEntry['category']
): MetricCatalogEntry[] {
  return catalog.filter(m => m.category === category)
}
